//
// File generated by rootcint at Thu Jan  3 14:38:58 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdIsrcdIEvtDisplayRootDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EvtDisplayRootDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void EventDisplay3D_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void EventDisplay3D_Dictionary();
   static void *new_EventDisplay3D(void *p = 0);
   static void *newArray_EventDisplay3D(Long_t size, void *p);
   static void delete_EventDisplay3D(void *p);
   static void deleteArray_EventDisplay3D(void *p);
   static void destruct_EventDisplay3D(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EventDisplay3D*)
   {
      ::EventDisplay3D *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::EventDisplay3D),0);
      static ::ROOT::TGenericClassInfo 
         instance("EventDisplay3D", "./include/EventDisplay3D.hh", 26,
                  typeid(::EventDisplay3D), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &EventDisplay3D_Dictionary, isa_proxy, 0,
                  sizeof(::EventDisplay3D) );
      instance.SetNew(&new_EventDisplay3D);
      instance.SetNewArray(&newArray_EventDisplay3D);
      instance.SetDelete(&delete_EventDisplay3D);
      instance.SetDeleteArray(&deleteArray_EventDisplay3D);
      instance.SetDestructor(&destruct_EventDisplay3D);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EventDisplay3D*)
   {
      return GenerateInitInstanceLocal((::EventDisplay3D*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EventDisplay3D*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void EventDisplay3D_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::EventDisplay3D*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void EventDisplay2D_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void EventDisplay2D_Dictionary();
   static void delete_EventDisplay2D(void *p);
   static void deleteArray_EventDisplay2D(void *p);
   static void destruct_EventDisplay2D(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EventDisplay2D*)
   {
      ::EventDisplay2D *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::EventDisplay2D),0);
      static ::ROOT::TGenericClassInfo 
         instance("EventDisplay2D", "./include/EventDisplay2D.hh", 35,
                  typeid(::EventDisplay2D), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &EventDisplay2D_Dictionary, isa_proxy, 0,
                  sizeof(::EventDisplay2D) );
      instance.SetDelete(&delete_EventDisplay2D);
      instance.SetDeleteArray(&deleteArray_EventDisplay2D);
      instance.SetDestructor(&destruct_EventDisplay2D);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EventDisplay2D*)
   {
      return GenerateInitInstanceLocal((::EventDisplay2D*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EventDisplay2D*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void EventDisplay2D_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::EventDisplay2D*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_EventDisplay3D(void *p) {
      return  p ? new(p) ::EventDisplay3D : new ::EventDisplay3D;
   }
   static void *newArray_EventDisplay3D(Long_t nElements, void *p) {
      return p ? new(p) ::EventDisplay3D[nElements] : new ::EventDisplay3D[nElements];
   }
   // Wrapper around operator delete
   static void delete_EventDisplay3D(void *p) {
      delete ((::EventDisplay3D*)p);
   }
   static void deleteArray_EventDisplay3D(void *p) {
      delete [] ((::EventDisplay3D*)p);
   }
   static void destruct_EventDisplay3D(void *p) {
      typedef ::EventDisplay3D current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::EventDisplay3D

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_EventDisplay2D(void *p) {
      delete ((::EventDisplay2D*)p);
   }
   static void deleteArray_EventDisplay2D(void *p) {
      delete [] ((::EventDisplay2D*)p);
   }
   static void destruct_EventDisplay2D(void *p) {
      typedef ::EventDisplay2D current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::EventDisplay2D

/********************************************************
* ./src/EvtDisplayRootDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEvtDisplayRootDict();

extern "C" void G__set_cpp_environmentEvtDisplayRootDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("EventDisplay3D.hh");
  G__add_compiledheader("EventDisplay2D.hh");
  G__cpp_reset_tagtableEvtDisplayRootDict();
}
#include <new>
extern "C" int G__cpp_dllrevEvtDisplayRootDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EventDisplay3D */
static int G__EvtDisplayRootDict_970_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EventDisplay3D* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EventDisplay3D[n];
     } else {
       p = new((void*) gvp) EventDisplay3D[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EventDisplay3D;
     } else {
       p = new((void*) gvp) EventDisplay3D;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay3D));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_970_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay3D*) G__getstructoffset())->PlotEvent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_970_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay3D*) G__getstructoffset())->AddPMTHit((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_970_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay3D*) G__getstructoffset())->AddLAPPDHit((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_970_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay3D*) G__getstructoffset())->ClearPMTHits();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_970_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay3D*) G__getstructoffset())->ClearLAPPDHits();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_970_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay3D*) G__getstructoffset())->DrawDetector();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_970_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay3D*) G__getstructoffset())->SetTimeRanges((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EvtDisplayRootDict_970_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EventDisplay3D* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EventDisplay3D(*(EventDisplay3D*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay3D));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EventDisplay3D G__TEventDisplay3D;
static int G__EvtDisplayRootDict_970_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EventDisplay3D*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EventDisplay3D*) (soff+(sizeof(EventDisplay3D)*i)))->~G__TEventDisplay3D();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EventDisplay3D*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EventDisplay3D*) (soff))->~G__TEventDisplay3D();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EvtDisplayRootDict_970_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EventDisplay3D* dest = (EventDisplay3D*) G__getstructoffset();
   *dest = *(EventDisplay3D*) libp->para[0].ref;
   const EventDisplay3D& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* EventDisplay2D */
static int G__EvtDisplayRootDict_1041_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EventDisplay2D* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new EventDisplay2D(*((TString*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) EventDisplay2D(*((TString*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay2D));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->SetHits(*((vector<vector<double> >*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->SetAzimuth(*((vector<vector<double> >*) G__int(libp->para[0])), *((vector<vector<double> >*) G__int(libp->para[1]))
, *((vector<vector<double> >*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->SetGeometry((int) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->SetPMTGeometry((int) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (bool) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->SetTrueTrackParams(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->SetPlots((TH1D*) G__int(libp->para[0]), (TH1D*) G__int(libp->para[1])
, (TH1D*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->PlotEventBarrel(*((string*) G__int(libp->para[0])), (bool) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (bool) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->PlotEventCube(*((string*) G__int(libp->para[0])), (bool) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (bool) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->PlotEventThetaPhi(*((string*) G__int(libp->para[0])), (bool) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (bool) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->PlotEventTime(*((string*) G__int(libp->para[0])), (bool) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (bool) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->doAzimuthalPlots((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, *((string*) G__int(libp->para[2])), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EventDisplay2D*) G__getstructoffset())->InitializeStyle();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EventDisplay2D*) G__getstructoffset())->MakeCanvas((int) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, libp->para[2].ref ? *(TH2D**) libp->para[2].ref : *(TH2D**) (void*) (&G__Mlong(libp->para[2]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EventDisplay2D*) G__getstructoffset())->MakeCanvasCylinder(*((TString*) G__int(libp->para[0])), libp->para[1].ref ? *(TH2D**) libp->para[1].ref : *(TH2D**) (void*) (&G__Mlong(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EventDisplay2D*) G__getstructoffset())->MakeCanvasCube(*((TString*) G__int(libp->para[0])), libp->para[1].ref ? *(TH2D**) libp->para[1].ref : *(TH2D**) (void*) (&G__Mlong(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EventDisplay2D*) G__getstructoffset())->MakeCanvasThetaPhi(*((TString*) G__int(libp->para[0])), libp->para[1].ref ? *(TH2D**) libp->para[1].ref : *(TH2D**) (void*) (&G__Mlong(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvtDisplayRootDict_1041_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EventDisplay2D*) G__getstructoffset())->MakeCanvasTime(*((TString*) G__int(libp->para[0])), libp->para[1].ref ? *(TH2D**) libp->para[1].ref : *(TH2D**) (void*) (&G__Mlong(libp->para[1]))));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EvtDisplayRootDict_1041_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EventDisplay2D* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EventDisplay2D(*(EventDisplay2D*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay2D));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EventDisplay2D G__TEventDisplay2D;
static int G__EvtDisplayRootDict_1041_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EventDisplay2D*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EventDisplay2D*) (soff+(sizeof(EventDisplay2D)*i)))->~G__TEventDisplay2D();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EventDisplay2D*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EventDisplay2D*) (soff))->~G__TEventDisplay2D();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EvtDisplayRootDict_1041_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EventDisplay2D* dest = (EventDisplay2D*) G__getstructoffset();
   *dest = *(EventDisplay2D*) libp->para[0].ref;
   const EventDisplay2D& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EventDisplay3D */

/* EventDisplay2D */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEvtDisplayRootDict {
 public:
  G__Sizep2memfuncEvtDisplayRootDict(): p(&G__Sizep2memfuncEvtDisplayRootDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEvtDisplayRootDict::*p)();
};

size_t G__get_sizep2memfuncEvtDisplayRootDict()
{
  G__Sizep2memfuncEvtDisplayRootDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEvtDisplayRootDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay3D))) {
     EventDisplay3D *G__Lderived;
     G__Lderived=(EventDisplay3D*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay3D),G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEvtDisplayRootDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Int_t,TGeoElementRN*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TGeoElementRN*,less<int> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ThreadData_t*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGeoVolumeAssembly::ThreadData_t*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<long,TGeoNavigatorArray*,less<long> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<Long_t,Int_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TEveElement*,Int_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplETEveElementmUcOintcOlesslETEveElementmUgRcOallocatorlEpairlETEveElementmUsPconstcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TEveElement*,int>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplETEveElementmUcOintcOlesslETEveElementmUgRcOallocatorlEpairlETEveElementmUsPconstcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TEveElement*,int,less<TEveElement*> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_maplETEveElementmUcOintcOlesslETEveElementmUgRcOallocatorlEpairlETEveElementmUsPconstcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<TEveProjected*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_listlETEveProjectedmUcOallocatorlETEveProjectedmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<TEveElement*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_setlETEveElementmUcOlesslETEveElementmUgRcOallocatorlETEveElementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<TEveElement*,less<TEveElement*> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_setlETEveElementmUcOlesslETEveElementmUgRcOallocatorlETEveElementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<TEveListTreeInfo>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_setlETEveElementcLcLTEveListTreeInfocOlesslETEveElementcLcLTEveListTreeInfogRcOallocatorlETEveElementcLcLTEveListTreeInfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<TEveElement::TEveListTreeInfo>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_setlETEveElementcLcLTEveListTreeInfocOlesslETEveElementcLcLTEveListTreeInfogRcOallocatorlETEveElementcLcLTEveListTreeInfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<TEveElement::TEveListTreeInfo,less<TEveElement::TEveListTreeInfo> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_setlETEveElementcLcLTEveListTreeInfocOlesslETEveElementcLcLTEveListTreeInfogRcOallocatorlETEveElementcLcLTEveListTreeInfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<TEveElement*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_listlETEveElementmUcOallocatorlETEveElementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TEveVectorT<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TEveVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TEveVectorT<Double_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TEveVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TEveVector4T<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TEveVector4TlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TEveVector4T<Double_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TEveVector4TlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TEveVector2T<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TEveVector2TlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TEveVector2T<Double_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TEveVector2TlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TEveVector2>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TEveVector2T<float> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("list<TGeoShape*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_listlETGeoShapemUcOallocatorlETGeoShapemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TArrayC*>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETArrayCmUcOallocatorlETArrayCmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETArrayCmUcOallocatorlETArrayCmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETArrayCmUcOallocatorlETArrayCmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETArrayCmUcOallocatorlETArrayCmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlETArrayCmUcOallocatorlETArrayCmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<Int_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EventDisplay3D */
static void G__setup_memvarEventDisplay3D(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay3D));
   { EventDisplay3D *p; p=(EventDisplay3D*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->TimeRangeSet)-(long)(p)),103,0,0,-1,-1,-1,1,"TimeRangeSet=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"PMTX=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"PMTY=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"PMTZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"PMTT=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"PMTQ=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"LAPPDX=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"LAPPDY=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"LAPPDZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"LAPPDT=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"LAPPDQ=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_tb[8]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TGeoManager),-1,-1,4,"geom=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TGeoMaterial),-1,-1,4,"matVacuum=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TGeoMaterial),-1,-1,4,"matWater=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TGeoMedium),-1,-1,4,"Vacuum=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TGeoMedium),-1,-1,4,"Water=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TGeoVolume),-1,-1,4,"top=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* EventDisplay2D */
static void G__setup_memvarEventDisplay2D(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay2D));
   { EventDisplay2D *p; p=(EventDisplay2D*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TString),-1,-1,4,"_iname=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fScale=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_isweighted=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_smeared=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_initiatedPMTGeo=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_initiatedDetectorGeo=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_setThePlots=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_openedoutfile=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_settruetrackparams=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_setazimuth=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,4,"theHits=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,4,"_tresid=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,4,"_azimuth=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,4,"_ttheta=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"truetrack=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fittrack=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_pmt_type=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_spatialcoverage=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_PMTdiameter=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_spatialresolving=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_detectortype=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_d1=",0,"diameter if cylindrical");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_d2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_d3=",0,"only used for mailbox geometry");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_clearance=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TStyle),-1,-1,4,"rootStyle=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH1D),-1,-1,4,"pointresidualDist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH1D),-1,-1,4,"trackresidualDist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH1D),-1,-1,4,"trackposDist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH1D),-1,-1,4,"trackthetaDist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH2D),-1,-1,4,"azimuthvstresid=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH2D),-1,-1,4,"azimuthvstheta=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH1D),-1,-1,4,"azimuthmeanprofile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH1D),-1,-1,4,"azimuthrmsprofile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH1D),-1,-1,4,"azimuthpeakprofile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TH1D),-1,-1,4,"azimuthFWHMprofile=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEvtDisplayRootDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEventDisplay3D(void) {
   /* EventDisplay3D */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay3D));
   G__memfunc_setup("EventDisplay3D",1359,G__EvtDisplayRootDict_970_0_1, 105, G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay3D), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotEvent",929,G__EvtDisplayRootDict_970_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddPMTHit",799,G__EvtDisplayRootDict_970_0_3, 121, -1, -1, 0, 5, 1, 1, 0, 
"d - - 0 - x d - - 0 - y "
"d - - 0 - z d - - 0 - t "
"d - - 0 - q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddLAPPDHit",927,G__EvtDisplayRootDict_970_0_4, 121, -1, -1, 0, 5, 1, 1, 0, 
"d - - 0 - x d - - 0 - y "
"d - - 0 - z d - - 0 - t "
"d - - 0 - q", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearPMTHits",1136,G__EvtDisplayRootDict_970_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearLAPPDHits",1264,G__EvtDisplayRootDict_970_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DrawDetector",1224,G__EvtDisplayRootDict_970_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimeRanges",1307,G__EvtDisplayRootDict_970_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - min d - - 0 - max", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("EventDisplay3D", 1359, G__EvtDisplayRootDict_970_0_9, (int) ('i'), G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay3D), -1, 0, 1, 1, 1, 0, "u 'EventDisplay3D' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EventDisplay3D", 1485, G__EvtDisplayRootDict_970_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EvtDisplayRootDict_970_0_11, (int) ('u'), G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay3D), -1, 1, 1, 1, 1, 0, "u 'EventDisplay3D' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncEventDisplay2D(void) {
   /* EventDisplay2D */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay2D));
   G__memfunc_setup("EventDisplay2D",1358,G__EvtDisplayRootDict_1041_0_1, 105, G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay2D), -1, 0, 1, 1, 1, 0, "u 'TString' - 0 - iname", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHits",708,G__EvtDisplayRootDict_1041_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<vector<double> >' 0 - ihits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAzimuth",1038,G__EvtDisplayRootDict_1041_0_3, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<vector<double> >' 0 - tresid u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<vector<double> >' 0 - azimuth "
"u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<vector<double> >' 0 - tracktheta", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGeometry",1144,G__EvtDisplayRootDict_1041_0_4, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - type d - - 0 - d1 "
"d - - 0 - d2 d - - 0 - d3 "
"d - - 0 - clearance", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPMTGeometry",1385,G__EvtDisplayRootDict_1041_0_5, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - pmttype d - - 0 - diameter "
"d - - 0 - coverage g - - 0 - spatialresolving", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTrueTrackParams",1829,G__EvtDisplayRootDict_1041_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - tparams", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPlots",830,G__EvtDisplayRootDict_1041_0_7, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TH1D' - 0 - trD U 'TH1D' - 0 - tpD "
"U 'TH1D' - 0 - ttD", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotEventBarrel",1529,G__EvtDisplayRootDict_1041_0_8, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'string' - 0 - savename g - - 0 - savecanvas "
"d - - 0 - lowt d - - 0 - hight "
"g - - 0 - dowrite", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotEventCube",1312,G__EvtDisplayRootDict_1041_0_9, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'string' - 0 - savename g - - 0 - savecanvas "
"d - - 0 - lowt d - - 0 - hight "
"g - - 0 - dowrite", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotEventThetaPhi",1720,G__EvtDisplayRootDict_1041_0_10, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'string' - 0 - savename g - - 0 - savecanvas "
"d - - 0 - lowt d - - 0 - hight "
"g - - 0 - dowrite", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlotEventTime",1328,G__EvtDisplayRootDict_1041_0_11, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'string' - 0 - savename g - - 0 - savecanvas "
"d - - 0 - lowt d - - 0 - hight "
"g - - 0 - dowrite", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("doAzimuthalPlots",1684,G__EvtDisplayRootDict_1041_0_12, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - tbins i - - 0 - phibins "
"u 'string' - 0 - savename d - - 0 - lowt "
"d - - 0 - hight", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitializeStyle",1571,G__EvtDisplayRootDict_1041_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeCanvas",986,G__EvtDisplayRootDict_1041_0_14, 85, G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TCanvas), -1, 0, 3, 1, 1, 0, 
"i - - 0 - ctype u 'TString' - 0 - namestring "
"U 'TH2D' - 1 - iwcDisplay", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeCanvasCylinder",1812,G__EvtDisplayRootDict_1041_0_15, 85, G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TCanvas), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - namestring U 'TH2D' - 1 - iwcDisplay", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeCanvasCube",1369,G__EvtDisplayRootDict_1041_0_16, 85, G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TCanvas), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - namestring U 'TH2D' - 1 - iwcDisplay", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeCanvasThetaPhi",1777,G__EvtDisplayRootDict_1041_0_17, 85, G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TCanvas), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - namestring U 'TH2D' - 1 - iwcDisplay", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeCanvasTime",1385,G__EvtDisplayRootDict_1041_0_18, 85, G__get_linked_tagnum(&G__EvtDisplayRootDictLN_TCanvas), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - namestring U 'TH2D' - 1 - iwcDisplay", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("EventDisplay2D", 1358, G__EvtDisplayRootDict_1041_0_19, (int) ('i'), G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay2D), -1, 0, 1, 1, 1, 0, "u 'EventDisplay2D' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EventDisplay2D", 1484, G__EvtDisplayRootDict_1041_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EvtDisplayRootDict_1041_0_21, (int) ('u'), G__get_linked_tagnum(&G__EvtDisplayRootDictLN_EventDisplay2D), -1, 1, 1, 1, 1, 0, "u 'EventDisplay2D' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEvtDisplayRootDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEvtDisplayRootDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {
}

static void G__cpp_setup_func36() {
}

static void G__cpp_setup_func37() {
}

static void G__cpp_setup_func38() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEvtDisplayRootDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
  G__cpp_setup_func36();
  G__cpp_setup_func37();
  G__cpp_setup_func38();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EvtDisplayRootDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR = { "map<long,int,less<long>,allocator<pair<const long,int> > >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR = { "map<int,TGeoElementRN*,less<int>,allocator<pair<const int,TGeoElementRN*> > >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TGeoMaterial = { "TGeoMaterial" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TGeoMedium = { "TGeoMedium" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TGeoVolume = { "TGeoVolume" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TGeoManager = { "TGeoManager" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR = { "vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGeoVolumeAssembly::ThreadData_t*,allocator<TGeoVolumeAssembly::ThreadData_t*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR = { "map<long,TGeoNavigatorArray*,less<long>,allocator<pair<const long,TGeoNavigatorArray*> > >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR = { "set<int,less<int>,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_maplETEveElementmUcOintcOlesslETEveElementmUgRcOallocatorlEpairlETEveElementmUsPconstcOintgRsPgRsPgR = { "map<TEveElement*,int,less<TEveElement*>,allocator<pair<TEveElement* const,int> > >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_listlETEveProjectedmUcOallocatorlETEveProjectedmUgRsPgR = { "list<TEveProjected*,allocator<TEveProjected*> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_setlETEveElementmUcOlesslETEveElementmUgRcOallocatorlETEveElementmUgRsPgR = { "set<TEveElement*,less<TEveElement*>,allocator<TEveElement*> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_setlETEveElementcLcLTEveListTreeInfocOlesslETEveElementcLcLTEveListTreeInfogRcOallocatorlETEveElementcLcLTEveListTreeInfogRsPgR = { "set<TEveElement::TEveListTreeInfo,less<TEveElement::TEveListTreeInfo>,allocator<TEveElement::TEveListTreeInfo> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_listlETEveElementmUcOallocatorlETEveElementmUgRsPgR = { "list<TEveElement*,allocator<TEveElement*> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TEveVectorTlEfloatgR = { "TEveVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TEveVectorTlEdoublegR = { "TEveVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TEveVector4TlEfloatgR = { "TEveVector4T<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TEveVector4TlEdoublegR = { "TEveVector4T<double>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TEveVector2TlEfloatgR = { "TEveVector2T<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TEveVector2TlEdoublegR = { "TEveVector2T<double>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_vectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgR = { "vector<TEveVector2T<float>,allocator<TEveVector2T<float> > >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TEveVector2T<float>,allocator<TEveVector2T<float> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_listlETGeoShapemUcOallocatorlETGeoShapemUgRsPgR = { "list<TGeoShape*,allocator<TGeoShape*> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_vectorlETArrayCmUcOallocatorlETArrayCmUgRsPgR = { "vector<TArrayC*,allocator<TArrayC*> >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETArrayCmUcOallocatorlETArrayCmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TArrayC*,allocator<TArrayC*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_EventDisplay3D = { "EventDisplay3D" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TStyle = { "TStyle" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_TH2D = { "TH2D" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_EventDisplay2D = { "EventDisplay2D" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEvtDisplayRootDict() {
  G__EvtDisplayRootDictLN_TObject.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TString.tagnum = -1 ;
  G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_string.tagnum = -1 ;
  G__EvtDisplayRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TH1D.tagnum = -1 ;
  G__EvtDisplayRootDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TGeoMaterial.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TGeoMedium.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TGeoVolume.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TGeoManager.tagnum = -1 ;
  G__EvtDisplayRootDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_maplETEveElementmUcOintcOlesslETEveElementmUgRcOallocatorlEpairlETEveElementmUsPconstcOintgRsPgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_listlETEveProjectedmUcOallocatorlETEveProjectedmUgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_setlETEveElementmUcOlesslETEveElementmUgRcOallocatorlETEveElementmUgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_setlETEveElementcLcLTEveListTreeInfocOlesslETEveElementcLcLTEveListTreeInfogRcOallocatorlETEveElementcLcLTEveListTreeInfogRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_listlETEveElementmUcOallocatorlETEveElementmUgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TCanvas.tagnum = -1 ;
  G__EvtDisplayRootDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TEveVectorTlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TEveVectorTlEdoublegR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TEveVector4TlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TEveVector4TlEdoublegR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TEveVector2TlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TEveVector2TlEdoublegR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_vectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_listlETGeoShapemUcOallocatorlETGeoShapemUgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_vectorlETArrayCmUcOallocatorlETArrayCmUgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETArrayCmUcOallocatorlETArrayCmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_EventDisplay3D.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TStyle.tagnum = -1 ;
  G__EvtDisplayRootDictLN_TH2D.tagnum = -1 ;
  G__EvtDisplayRootDictLN_EventDisplay2D.tagnum = -1 ;
  G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEvtDisplayRootDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TString);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_string);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_maplElongcOintcOlesslElonggRcOallocatorlEpairlEconstsPlongcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TGeoMaterial);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TGeoMedium);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TGeoVolume);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TGeoManager);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_maplElongcOTGeoNavigatorArraymUcOlesslElonggRcOallocatorlEpairlEconstsPlongcOTGeoNavigatorArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_setlEintcOlesslEintgRcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_maplETEveElementmUcOintcOlesslETEveElementmUgRcOallocatorlEpairlETEveElementmUsPconstcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_listlETEveProjectedmUcOallocatorlETEveProjectedmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_setlETEveElementmUcOlesslETEveElementmUgRcOallocatorlETEveElementmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_setlETEveElementcLcLTEveListTreeInfocOlesslETEveElementcLcLTEveListTreeInfogRcOallocatorlETEveElementcLcLTEveListTreeInfogRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_listlETEveElementmUcOallocatorlETEveElementmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TEveVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TEveVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TEveVector4TlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TEveVector4TlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TEveVector2TlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TEveVector2TlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_vectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETEveVector2TlEfloatgRcOallocatorlETEveVector2TlEfloatgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_listlETGeoShapemUcOallocatorlETGeoShapemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_vectorlETArrayCmUcOallocatorlETArrayCmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlETArrayCmUcOallocatorlETArrayCmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_EventDisplay3D),sizeof(EventDisplay3D),-1,29952,(char*)NULL,G__setup_memvarEventDisplay3D,G__setup_memfuncEventDisplay3D);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TStyle);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_TH2D);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_EventDisplay2D),sizeof(EventDisplay2D),-1,33792,(char*)NULL,G__setup_memvarEventDisplay2D,G__setup_memfuncEventDisplay2D);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvtDisplayRootDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupEvtDisplayRootDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEvtDisplayRootDict()");
  G__set_cpp_environmentEvtDisplayRootDict();
  G__cpp_setup_tagtableEvtDisplayRootDict();

  G__cpp_setup_inheritanceEvtDisplayRootDict();

  G__cpp_setup_typetableEvtDisplayRootDict();

  G__cpp_setup_memvarEvtDisplayRootDict();

  G__cpp_setup_memfuncEvtDisplayRootDict();
  G__cpp_setup_globalEvtDisplayRootDict();
  G__cpp_setup_funcEvtDisplayRootDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEvtDisplayRootDict();
  return;
}
class G__cpp_setup_initEvtDisplayRootDict {
  public:
    G__cpp_setup_initEvtDisplayRootDict() { G__add_setup_func("EvtDisplayRootDict",(G__incsetup)(&G__cpp_setupEvtDisplayRootDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEvtDisplayRootDict() { G__remove_setup_func("EvtDisplayRootDict"); }
};
G__cpp_setup_initEvtDisplayRootDict G__cpp_setup_initializerEvtDisplayRootDict;

